CREATE TABLE IF NOT EXISTS `Locations` (
  `LocationID` BIGINT NOT NULL AUTO_INCREMENT,
  `Address` VARCHAR(255) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Building` VARCHAR(45) NOT NULL,
  `Floor` VARCHAR(45) NULL,
  `google_maps_url` VARCHAR(255) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LocationID`)
);