CREATE TABLE IF NOT EXISTS `Bundles` (
  `BundleID` BIGINT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(12,2) NOT NULL,
  `data_cap` INT NOT NULL DEFAULT 0,
  `Speed` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BundleID`)
);