CREATE TABLE IF NOT EXISTS `Bundles` (
  `bundle_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `data_cap` INT NOT NULL DEFAULT 0,
  `speed` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`bundle_id`)
);