ALTER TABLE `Bundles`
ADD COLUMN `deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `Users`
ADD COLUMN `deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `UserBundles`
ADD COLUMN `deleted` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE Payments
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

